[phases.setup]
nixPkgs = ['openjdk17']

[phases.build]
cmds = ['./gradlew clean build -x test']

[start]
cmd = 'java -Dserver.port=$PORT -Dspring.profiles.active=prod -Dapp.version=${APP_VERSION:-unknown} -Dapp.commit.hash=${COMMIT_HASH:-unknown} -jar build/libs/slotify-backend-*.jar'